### PR TITLE
[API-3499] Invoke configured hook address when dispatching hyperlane message

### PR DESCRIPTION
**Pull request by dhfang**
- store hyperlane hook address in contract state
- specify the hook in the hyperlane dispatch message

### CODE REVIEW

**Comment by dhfang** [comment]
@thal0x should I be making the same change to the solidity side for symmetry? if so, i'm not sure where the hook is specified in the solidity mailbox dispatch method arguments https://github.com/skip-mev/go-fast-contracts/blob/main/solidity/src/interfaces/hyperlane/IMailbox.sol#L54-L55

**Comment by thal0x** [comment]
I know it's not necessarily important at the moment but for the sake of symmetry should we add this change to the Solidity contracts as well?

**Comment by thal0x** [comment]
Lets just create a Linear task for adding this to the Solidity contract, it's a little unclear to me and doesn't feel worth spending time on right now IMO. But let me know if you disagree

**Review by thal0x — APPROVED** [review]

**Comment by dhfang** [comment]
Sounds good to me

**Pull request merged**
